'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Stories', [
      { id: 1, title: "Learning How to Code", body: "Pokem ipsum dolor sit amet Skarmory Cacnea Lumineon Bronzor Scolipede Pidgeot. Pokemon The Movie 2000 Durant Altaria Swift Poliwag Archeops Stunfisk. Pokemon Heroes Togetic Dewgong Metagross Ariados Kricketot Cacturne. Charmeleon Ice Berry Ho-oh Cascoon Donphan Great Ball Arceus. Pewter City Goldeen Water Gun Squirtle Torkoal quis nostrud exercitation Gloom. Charizard Solrock Volbeat Noctowl Simipour Body Slam Staravia. Ruby Politoed Storm Badge Slakoth Rotom et dolore magna aliqua Remoraid. Ghost Swoobat Walrein Ninetales Mewtwo Thundershock Luvdisc. Cascade Badge Magmortar sunt in culpa qui officia Silcoon Gothita Poison Sting Meditite. Sonic Boom Tropius Plusle Snivy Banette Poliwhirl Ninetales. Water Gun Beedrill Rotom Jellicent Cubchoo Cryogonal anim id est laborum. Razor Leaf Remoraid Blastoise Pokemon 4Ever Drapion S.S. Anne Quilava. Misty Koffing Floatzel Wartortle Giratina Dunsparce Escape Rope. Plain Badge Galvantula Shuppet Cyndaquil Combee Roserade Pokemon Fan Club Chairman. Charizard Latias Sharpedo Tornadus Lickitung Taillow Whimsicott.", userId: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 2, title: "How to Ride a Bike", body: "Pokem ipsum dolor sit amet Skarmory Cacnea Lumineon Bronzor Scolipede Pidgeot. Pokemon The Movie 2000 Durant Altaria Swift Poliwag Archeops Stunfisk. Pokemon Heroes Togetic Dewgong Metagross Ariados Kricketot Cacturne. Charmeleon Ice Berry Ho-oh Cascoon Donphan Great Ball Arceus. Pewter City Goldeen Water Gun Squirtle Torkoal quis nostrud exercitation Gloom. Charizard Solrock Volbeat Noctowl Simipour Body Slam Staravia. Ruby Politoed Storm Badge Slakoth Rotom et dolore magna aliqua Remoraid. Ghost Swoobat Walrein Ninetales Mewtwo Thundershock Luvdisc. Cascade Badge Magmortar sunt in culpa qui officia Silcoon Gothita Poison Sting Meditite. Sonic Boom Tropius Plusle Snivy Banette Poliwhirl Ninetales. Water Gun Beedrill Rotom Jellicent Cubchoo Cryogonal anim id est laborum. Razor Leaf Remoraid Blastoise Pokemon 4Ever Drapion S.S. Anne Quilava. Misty Koffing Floatzel Wartortle Giratina Dunsparce Escape Rope. Plain Badge Galvantula Shuppet Cyndaquil Combee Roserade Pokemon Fan Club Chairman. Charizard Latias Sharpedo Tornadus Lickitung Taillow Whimsicott.", userId: 2, createdAt: new Date(), updatedAt: new Date() },
      { id: 3, title: "Fun Things to Do During Quarantine", body: "Pokem ipsum dolor sit amet Skarmory Cacnea Lumineon Bronzor Scolipede Pidgeot. Pokemon The Movie 2000 Durant Altaria Swift Poliwag Archeops Stunfisk. Pokemon Heroes Togetic Dewgong Metagross Ariados Kricketot Cacturne. Charmeleon Ice Berry Ho-oh Cascoon Donphan Great Ball Arceus. Pewter City Goldeen Water Gun Squirtle Torkoal quis nostrud exercitation Gloom. Charizard Solrock Volbeat Noctowl Simipour Body Slam Staravia. Ruby Politoed Storm Badge Slakoth Rotom et dolore magna aliqua Remoraid. Ghost Swoobat Walrein Ninetales Mewtwo Thundershock Luvdisc. Cascade Badge Magmortar sunt in culpa qui officia Silcoon Gothita Poison Sting Meditite. Sonic Boom Tropius Plusle Snivy Banette Poliwhirl Ninetales. Water Gun Beedrill Rotom Jellicent Cubchoo Cryogonal anim id est laborum. Razor Leaf Remoraid Blastoise Pokemon 4Ever Drapion S.S. Anne Quilava. Misty Koffing Floatzel Wartortle Giratina Dunsparce Escape Rope. Plain Badge Galvantula Shuppet Cyndaquil Combee Roserade Pokemon Fan Club Chairman. Charizard Latias Sharpedo Tornadus Lickitung Taillow Whimsicott.", userId: 2, createdAt: new Date(), updatedAt: new Date() },
    ], {});
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('Stories', null, {});
  }
};
